"""Embedding the Runtime Kit (``p2e_runtime``) in the EXE being built.

For a build with any service on, the converter writes three things into
``<output>/build/p2e_runtime_kit/<name>/``:

* ``p2e_runtime.json`` — the services and their settings, as data;
* ``p2e_runtime_hook.py`` — a fixed two-line runtime hook that imports the
  package and calls ``install()``; it holds no configuration at all;
* ``lib/p2e_runtime/`` — a copy of the package, so the build finds it even in
  an isolated environment, and only it (adding the converter's own
  site-packages to the search path would defeat the isolation).

and passes them to PyInstaller with ``--runtime-hook``, ``--add-data`` and
``--paths``, plus one hidden import per enabled service: the package imports
its services by name, so a service that is off adds nothing to the EXE.

These options are added to the command at build time. They are never stored
in ``extra_args`` or anywhere in a settings file, which is why the
``--runtime-hook`` the converter writes itself does not trip the untrusted
settings warning while one inside ``extra_args`` still does.

UI-independent: texts shown by the runtime (crash dialog, "already running")
are passed in already translated.
"""

import json
import os
import shutil
import sys
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from py2exe_gui.core.builder import _add_data_separator, split_extra_args
from py2exe_gui.core.config import BuildConfig, RuntimeKitConfig
from py2exe_gui.core.diagnostics import build_name, build_root
from py2exe_gui.core.fixes import SEVERITY_ERROR, SEVERITY_INFO, Finding
from py2exe_gui.core.update_signing import is_public_key

PACKAGE = "p2e_runtime"
CONFIG_FILE_NAME = "p2e_runtime.json"
HOOK_FILE_NAME = "p2e_runtime_hook.py"
KIT_FOLDER = "p2e_runtime_kit"

#: The service module PyInstaller must bundle for each service.
SERVICE_MODULES = {
    "resource_path": "",  # p2e_runtime.paths, always imported by the package
    "log_redirect": "p2e_runtime.logs",
    "crash_reporter": "p2e_runtime.crash",
    "single_instance": "p2e_runtime.single_instance",
    "updater": "p2e_runtime.updates",
}

#: Keys of the translated texts the runtime shows (see ``runtime_texts``).
TEXT_KEYS = (
    "crash_title", "crash_message", "support_prompt", "instance_message",
    "update_title", "update_message",
)

HOOK_SOURCE = (
    "# Runtime Kit hook, generated by Python to EXE Converter.\n"
    "# It holds no settings: those are in p2e_runtime.json, bundled as data.\n"
    "import p2e_runtime\n"
    "\n"
    "p2e_runtime.install()\n"
)


# ── Validation ─────────────────────────────────────────────────────────────


def _is_acceptable_url(url: str, allow_insecure_localhost: bool = False) -> bool:
    # The runtime's own rule, so the converter never ships a URL it refuses.
    from p2e_runtime.updates import UpdateError, check_url

    try:
        check_url(url, allow_insecure_localhost)
    except UpdateError:
        return False
    return True


def _valid_version(text: str) -> bool:
    from p2e_runtime.updates import parse_version

    try:
        parse_version(text)
    except ValueError:
        return False
    return True


def validate(kit: RuntimeKitConfig, onefile: bool = True,
             allow_insecure_localhost: bool = False) -> List[Finding]:
    """What is wrong (errors) or worth knowing (info) about these settings.

    Errors stop the build: an updater without HTTPS or without a key would be
    shipped as a vulnerability rather than a feature.
    """
    findings: List[Finding] = []
    if kit.updater:
        url = kit.update_url.strip()
        if not url:
            findings.append(Finding("kit_update_url_missing", SEVERITY_ERROR))
        elif not _is_acceptable_url(url, allow_insecure_localhost):
            findings.append(Finding("kit_update_url_insecure", SEVERITY_ERROR, {"url": url}))
        key = kit.update_public_key.strip()
        if not key:
            findings.append(Finding("kit_update_key_missing", SEVERITY_ERROR))
        elif not is_public_key(key):
            findings.append(Finding("kit_update_key_invalid", SEVERITY_ERROR))
        if not _valid_version(kit.app_version):
            findings.append(
                Finding("kit_update_version_invalid", SEVERITY_ERROR,
                        {"version": kit.app_version or "—"})
            )
        if not onefile:
            findings.append(Finding("kit_update_needs_installer", SEVERITY_INFO))
    support = kit.support_url.strip()
    if kit.crash_reporter and support:
        from p2e_runtime.crash import is_safe_support_url

        if not is_safe_support_url(support):
            findings.append(Finding("kit_support_url_invalid", SEVERITY_ERROR, {"url": support}))
    return findings


def blocking(findings: List[Finding]) -> List[Finding]:
    return [f for f in findings if f.severity == SEVERITY_ERROR]


# ── The runtime's configuration ────────────────────────────────────────────


def runtime_config_dict(
    kit: RuntimeKitConfig,
    app_name: str,
    onefile: bool = True,
    texts: Optional[Dict[str, str]] = None,
    rtl: bool = False,
    diagnostic: bool = False,
    allow_insecure_localhost: bool = False,
) -> Dict[str, object]:
    """The content of ``p2e_runtime.json`` for ``kit``.

    ``diagnostic`` is for the doctor's diagnostic run, which must reproduce
    the app without stopping on a modal dialog or reaching the network: the
    crash dialog and the start-up update check are left out.
    ``allow_insecure_localhost`` exists for tests only and is never set from
    the UI or from a settings file.
    """
    texts = texts or {}
    services: Dict[str, object] = {}
    if kit.resource_path:
        services["resource_path"] = {}
    if kit.log_redirect:
        services["logs"] = {"max_bytes": 1024 * 1024, "backups": 3}
    if kit.crash_reporter:
        services["crash_reporter"] = {
            "dialog": not diagnostic,
            "support_url": kit.support_url.strip(),
            "title": texts.get("crash_title", ""),
            "message": texts.get("crash_message", ""),
            "support_prompt": texts.get("support_prompt", ""),
        }
    if kit.single_instance:
        services["single_instance"] = {
            "id": app_name,
            "message": kit.instance_message.strip() or texts.get("instance_message", ""),
            "exit_code": 0,
        }
    if kit.updater:
        updater: Dict[str, object] = {
            "manifest_url": kit.update_url.strip(),
            "public_key": kit.update_public_key.strip().lower(),
            "check_on_start": kit.update_check_on_start and not diagnostic,
            "installer_args": split_extra_args(kit.installer_args),
            "prompt_title": texts.get("update_title", ""),
            "prompt_message": texts.get("update_message", ""),
        }
        if allow_insecure_localhost:
            updater["allow_insecure_localhost"] = True
        services["updater"] = updater
    return {
        "format": 1,
        "app": {
            "name": app_name,
            "version": kit.app_version.strip(),
            "build": "onefile" if onefile else "onedir",
            "rtl": bool(rtl),
        },
        "services": services,
    }


def render_runtime_config(*args, **kwargs) -> str:
    return json.dumps(runtime_config_dict(*args, **kwargs), indent=2, ensure_ascii=False) + "\n"


def render_hook() -> str:
    return HOOK_SOURCE


# ── Files and PyInstaller options ──────────────────────────────────────────


def kit_dir_for(config: BuildConfig) -> str:
    """``<output>/build/p2e_runtime_kit/<name>``, beside PyInstaller's own work folder."""
    return os.path.join(build_root(config), "build", KIT_FOLDER, build_name(config))


def runtime_package_dir() -> str:
    """Folder holding the ``p2e_runtime`` *sources* to copy into the build.

    Normally the installed package. When the converter itself runs frozen,
    its modules have no source files, so the sources are expected as data
    in the bundle (``<bundle>/p2e_runtime``). '' when neither exists.
    """
    candidates = []
    try:
        import p2e_runtime

        candidates.append(os.path.dirname(os.path.abspath(p2e_runtime.__file__)))
    except ImportError:  # pragma: no cover - shipped together
        pass
    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        candidates.append(os.path.join(meipass, PACKAGE))
    for folder in candidates:
        if os.path.isfile(os.path.join(folder, "__init__.py")):
            return folder
    return ""


@dataclass
class KitFiles:
    kit_dir: str
    hook_path: str
    config_path: str
    lib_dir: str
    services: List[str] = field(default_factory=list)


def kit_files(config: BuildConfig) -> KitFiles:
    kit_dir = kit_dir_for(config)
    return KitFiles(
        kit_dir=kit_dir,
        hook_path=os.path.join(kit_dir, HOOK_FILE_NAME),
        config_path=os.path.join(kit_dir, CONFIG_FILE_NAME),
        lib_dir=os.path.join(kit_dir, "lib"),
        services=config.runtime_kit.enabled_services(),
    )


def pyinstaller_options(files: KitFiles, platform: Optional[str] = None) -> List[str]:
    """The options that embed the kit; empty when no service is on."""
    if not files.services:
        return []
    sep = _add_data_separator(platform)
    options = [
        "--runtime-hook", files.hook_path,
        "--add-data", f"{files.config_path}{sep}.",
        "--paths", files.lib_dir,
        "--hidden-import", PACKAGE,
    ]
    for service in files.services:
        module = SERVICE_MODULES.get(service)
        if module:
            options += ["--hidden-import", module]
    return options


def write_kit(
    config: BuildConfig,
    texts: Optional[Dict[str, str]] = None,
    rtl: bool = False,
    diagnostic: bool = False,
    allow_insecure_localhost: bool = False,
    platform: Optional[str] = None,
    package_dir: Optional[str] = None,
) -> Tuple[List[str], List[Finding]]:
    """Write the kit for ``config``; return (PyInstaller options, errors).

    No service on → ``([], [])`` and nothing is written. Any blocking problem
    → ``([], errors)`` and nothing is written either.
    """
    kit = config.runtime_kit
    if not kit.enabled:
        return [], []
    errors = blocking(validate(kit, config.onefile, allow_insecure_localhost))
    source_dir = package_dir if package_dir is not None else runtime_package_dir()
    if not source_dir:
        errors.append(Finding("kit_source_missing", SEVERITY_ERROR))
    if errors:
        return [], errors

    files = kit_files(config)
    target = os.path.join(files.lib_dir, PACKAGE)
    if os.path.isdir(target):
        shutil.rmtree(target)
    os.makedirs(target)
    for name in sorted(os.listdir(source_dir)):
        if name.endswith(".py"):
            shutil.copy2(os.path.join(source_dir, name), os.path.join(target, name))
    with open(files.config_path, "w", encoding="utf-8") as f:
        f.write(render_runtime_config(
            kit, build_name(config), config.onefile, texts, rtl,
            diagnostic=diagnostic, allow_insecure_localhost=allow_insecure_localhost,
        ))
    with open(files.hook_path, "w", encoding="utf-8") as f:
        f.write(render_hook())
    return pyinstaller_options(files, platform), []


def preview_options(config: BuildConfig, platform: Optional[str] = None) -> List[str]:
    """The options a build would add, without writing anything (command preview)."""
    if not config.runtime_kit.enabled:
        return []
    return pyinstaller_options(kit_files(config), platform)


# ── Settings someone else wrote ────────────────────────────────────────────


@dataclass(frozen=True)
class KitRisk:
    """Something in a shared settings file that changes what the EXE trusts."""

    code: str  # "foreign_update_key" | "support_url"
    params: Dict[str, str]


def untrusted_risks(kit: RuntimeKitConfig, own_public_key: str = "") -> List[KitRisk]:
    """What to show before applying a settings file the user did not write.

    The kit cannot inject code — it is flags and text — but an updater set to
    *someone else's* key and URL would make the user's EXE install whatever
    that person signs. That deserves the same confirmation as
    ``--runtime-hook``. The user's own key is not a risk.
    """
    from py2exe_gui.core.update_signing import fingerprint

    risks: List[KitRisk] = []
    key = kit.update_public_key.strip().lower()
    if kit.updater and key and key != (own_public_key or "").strip().lower():
        risks.append(KitRisk("foreign_update_key", {
            "key": fingerprint(key), "url": kit.update_url.strip(),
        }))
    if kit.crash_reporter and kit.support_url.strip():
        risks.append(KitRisk("support_url", {"url": kit.support_url.strip()}))
    return risks
